// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"back/internal/service/internal/dao/internal"
)

// goadminRolesDao is the data access object for table goadmin_roles.
// You can define custom methods on it to extend its functionality as you wish.
type goadminRolesDao struct {
	*internal.GoadminRolesDao
}

var (
	// GoadminRoles is globally public accessible object for table goadmin_roles operations.
	GoadminRoles = goadminRolesDao{
		internal.NewGoadminRolesDao(),
	}
)

// Fill with you ideas below.
