// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"back/internal/service/internal/dao/internal"
)

// goadminUsersDao is the data access object for table goadmin_users.
// You can define custom methods on it to extend its functionality as you wish.
type goadminUsersDao struct {
	*internal.GoadminUsersDao
}

var (
	// GoadminUsers is globally public accessible object for table goadmin_users operations.
	GoadminUsers = goadminUsersDao{
		internal.NewGoadminUsersDao(),
	}
)

// Fill with you ideas below.
