// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"back/internal/service/internal/dao/internal"
)

// goadminSiteDao is the data access object for table goadmin_site.
// You can define custom methods on it to extend its functionality as you wish.
type goadminSiteDao struct {
	*internal.GoadminSiteDao
}

var (
	// GoadminSite is globally public accessible object for table goadmin_site operations.
	GoadminSite = goadminSiteDao{
		internal.NewGoadminSiteDao(),
	}
)

// Fill with you ideas below.
