// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"back/internal/service/internal/dao/internal"
)

// goadminUserPermissionsDao is the data access object for table goadmin_user_permissions.
// You can define custom methods on it to extend its functionality as you wish.
type goadminUserPermissionsDao struct {
	*internal.GoadminUserPermissionsDao
}

var (
	// GoadminUserPermissions is globally public accessible object for table goadmin_user_permissions operations.
	GoadminUserPermissions = goadminUserPermissionsDao{
		internal.NewGoadminUserPermissionsDao(),
	}
)

// Fill with you ideas below.
