// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"back/internal/service/internal/dao/internal"
)

// goadminMenuDao is the data access object for table goadmin_menu.
// You can define custom methods on it to extend its functionality as you wish.
type goadminMenuDao struct {
	*internal.GoadminMenuDao
}

var (
	// GoadminMenu is globally public accessible object for table goadmin_menu operations.
	GoadminMenu = goadminMenuDao{
		internal.NewGoadminMenuDao(),
	}
)

// Fill with you ideas below.
