// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"back/internal/service/internal/dao/internal"
)

// goadminRoleUsersDao is the data access object for table goadmin_role_users.
// You can define custom methods on it to extend its functionality as you wish.
type goadminRoleUsersDao struct {
	*internal.GoadminRoleUsersDao
}

var (
	// GoadminRoleUsers is globally public accessible object for table goadmin_role_users operations.
	GoadminRoleUsers = goadminRoleUsersDao{
		internal.NewGoadminRoleUsersDao(),
	}
)

// Fill with you ideas below.
