// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"back/internal/service/internal/dao/internal"
)

// goadminRolePermissionsDao is the data access object for table goadmin_role_permissions.
// You can define custom methods on it to extend its functionality as you wish.
type goadminRolePermissionsDao struct {
	*internal.GoadminRolePermissionsDao
}

var (
	// GoadminRolePermissions is globally public accessible object for table goadmin_role_permissions operations.
	GoadminRolePermissions = goadminRolePermissionsDao{
		internal.NewGoadminRolePermissionsDao(),
	}
)

// Fill with you ideas below.
