// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"back/internal/service/internal/dao/internal"
)

// goadminPermissionsDao is the data access object for table goadmin_permissions.
// You can define custom methods on it to extend its functionality as you wish.
type goadminPermissionsDao struct {
	*internal.GoadminPermissionsDao
}

var (
	// GoadminPermissions is globally public accessible object for table goadmin_permissions operations.
	GoadminPermissions = goadminPermissionsDao{
		internal.NewGoadminPermissionsDao(),
	}
)

// Fill with you ideas below.
