// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"back/internal/service/internal/dao/internal"
)

// goadminSessionDao is the data access object for table goadmin_session.
// You can define custom methods on it to extend its functionality as you wish.
type goadminSessionDao struct {
	*internal.GoadminSessionDao
}

var (
	// GoadminSession is globally public accessible object for table goadmin_session operations.
	GoadminSession = goadminSessionDao{
		internal.NewGoadminSessionDao(),
	}
)

// Fill with you ideas below.
