// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"back/internal/service/internal/dao/internal"
)

// goadminRoleMenuDao is the data access object for table goadmin_role_menu.
// You can define custom methods on it to extend its functionality as you wish.
type goadminRoleMenuDao struct {
	*internal.GoadminRoleMenuDao
}

var (
	// GoadminRoleMenu is globally public accessible object for table goadmin_role_menu operations.
	GoadminRoleMenu = goadminRoleMenuDao{
		internal.NewGoadminRoleMenuDao(),
	}
)

// Fill with you ideas below.
