// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"back/internal/service/internal/dao/internal"
)

// ordersDao is the data access object for table orders.
// You can define custom methods on it to extend its functionality as you wish.
type ordersDao struct {
	*internal.OrdersDao
}

var (
	// Orders is globally public accessible object for table orders operations.
	Orders = ordersDao{
		internal.NewOrdersDao(),
	}
)

// Fill with you ideas below.
