// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"back/internal/service/internal/dao/internal"
)

// shoppingCartsDao is the data access object for table shopping_carts.
// You can define custom methods on it to extend its functionality as you wish.
type shoppingCartsDao struct {
	*internal.ShoppingCartsDao
}

var (
	// ShoppingCarts is globally public accessible object for table shopping_carts operations.
	ShoppingCarts = shoppingCartsDao{
		internal.NewShoppingCartsDao(),
	}
)

// Fill with you ideas below.
