// Code generated by entc, DO NOT EDIT.

package shoppingcart

import (
	"time"
)

const (
	// Label holds the string label denoting the shoppingcart type in the database.
	Label = "shopping_cart"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdateAt holds the string denoting the update_at field in the database.
	FieldUpdateAt = "update_at"
	// EdgeBook holds the string denoting the book edge name in mutations.
	EdgeBook = "book"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the shoppingcart in the database.
	Table = "shopping_carts"
	// BookTable is the table that holds the book relation/edge.
	BookTable = "shopping_carts"
	// BookInverseTable is the table name for the Book entity.
	// It exists in this package in order to avoid circular dependency with the "book" package.
	BookInverseTable = "books"
	// BookColumn is the table column denoting the book relation/edge.
	BookColumn = "book_shopping_cart"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "shopping_carts"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_shopping_cart"
)

// Columns holds all SQL columns for shoppingcart fields.
var Columns = []string{
	FieldID,
	FieldAmount,
	FieldCreatedAt,
	FieldUpdateAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "shopping_carts"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"book_shopping_cart",
	"user_shopping_cart",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdateAt holds the default value on creation for the "update_at" field.
	DefaultUpdateAt func() time.Time
	// UpdateDefaultUpdateAt holds the default value on update for the "update_at" field.
	UpdateDefaultUpdateAt func() time.Time
)
