version: "3"
services:
  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    volumes:
      - ./search/data.ms:/home/meili/data.ms

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 104494lw!
      MYSQL_DATABASE: bookstore
    command:
      --authentication_policy=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql