// This file is generated by GoAdmin CLI adm.
package tables

import (
	"github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"
)

// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "books" => http://localhost:9033/admin/info/books
// "categories" => http://localhost:9033/admin/info/categories
// "orders" => http://localhost:9033/admin/info/orders
// "shopping_carts" => http://localhost:9033/admin/info/shopping_carts
// "users" => http://localhost:9033/admin/info/users
//
// example end
var Generators = map[string]table.Generator{

	"books":          GetBooksTable,
	"categories":     GetCategoriesTable,
	"orders":         GetOrdersTable,
	"shopping_carts": GetShoppingCartsTable,
	"users":          GetUsersTable,

	// generators end
}
