// Code generated by entc, DO NOT EDIT.

package ent

import (
	"back/repository/ent/book"
	"back/repository/ent/order"
	"back/repository/ent/schema"
	"back/repository/ent/shoppingcart"
	"back/repository/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bookFields := schema.Book{}.Fields()
	_ = bookFields
	// bookDescCreatedAt is the schema descriptor for created_at field.
	bookDescCreatedAt := bookFields[7].Descriptor()
	// book.DefaultCreatedAt holds the default value on creation for the created_at field.
	book.DefaultCreatedAt = bookDescCreatedAt.Default.(func() time.Time)
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescCreatedAt is the schema descriptor for created_at field.
	orderDescCreatedAt := orderFields[2].Descriptor()
	// order.DefaultCreatedAt holds the default value on creation for the created_at field.
	order.DefaultCreatedAt = orderDescCreatedAt.Default.(func() time.Time)
	// orderDescUpdateAt is the schema descriptor for update_at field.
	orderDescUpdateAt := orderFields[3].Descriptor()
	// order.DefaultUpdateAt holds the default value on creation for the update_at field.
	order.DefaultUpdateAt = orderDescUpdateAt.Default.(func() time.Time)
	// order.UpdateDefaultUpdateAt holds the default value on update for the update_at field.
	order.UpdateDefaultUpdateAt = orderDescUpdateAt.UpdateDefault.(func() time.Time)
	shoppingcartFields := schema.ShoppingCart{}.Fields()
	_ = shoppingcartFields
	// shoppingcartDescCreatedAt is the schema descriptor for created_at field.
	shoppingcartDescCreatedAt := shoppingcartFields[1].Descriptor()
	// shoppingcart.DefaultCreatedAt holds the default value on creation for the created_at field.
	shoppingcart.DefaultCreatedAt = shoppingcartDescCreatedAt.Default.(func() time.Time)
	// shoppingcartDescUpdateAt is the schema descriptor for update_at field.
	shoppingcartDescUpdateAt := shoppingcartFields[2].Descriptor()
	// shoppingcart.DefaultUpdateAt holds the default value on creation for the update_at field.
	shoppingcart.DefaultUpdateAt = shoppingcartDescUpdateAt.Default.(func() time.Time)
	// shoppingcart.UpdateDefaultUpdateAt holds the default value on update for the update_at field.
	shoppingcart.UpdateDefaultUpdateAt = shoppingcartDescUpdateAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
}
