// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Book is the predicate function for book builders.
type Book func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// ShoppingCart is the predicate function for shoppingcart builders.
type ShoppingCart func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
