// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-10 14:06:06
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// GoadminRolePermissionsDao is the data access object for table goadmin_role_permissions.
type GoadminRolePermissionsDao struct {
	table   string                        // table is the underlying table name of the DAO.
	group   string                        // group is the database configuration group name of current DAO.
	columns GoadminRolePermissionsColumns // columns contains all the column names of Table for convenient usage.
}

// GoadminRolePermissionsColumns defines and stores column names for table goadmin_role_permissions.
type GoadminRolePermissionsColumns struct {
	RoleId       string //
	PermissionId string //
	CreatedAt    string //
	UpdatedAt    string //
}

//  goadminRolePermissionsColumns holds the columns for table goadmin_role_permissions.
var goadminRolePermissionsColumns = GoadminRolePermissionsColumns{
	RoleId:       "role_id",
	PermissionId: "permission_id",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
}

// NewGoadminRolePermissionsDao creates and returns a new DAO object for table data access.
func NewGoadminRolePermissionsDao() *GoadminRolePermissionsDao {
	return &GoadminRolePermissionsDao{
		group:   "default",
		table:   "goadmin_role_permissions",
		columns: goadminRolePermissionsColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *GoadminRolePermissionsDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *GoadminRolePermissionsDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *GoadminRolePermissionsDao) Columns() GoadminRolePermissionsColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *GoadminRolePermissionsDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *GoadminRolePermissionsDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *GoadminRolePermissionsDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
