// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-21 20:57:03
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// GoadminOperationLogDao is the data access object for table goadmin_operation_log.
type GoadminOperationLogDao struct {
	table   string                     // table is the underlying table name of the DAO.
	group   string                     // group is the database configuration group name of current DAO.
	columns GoadminOperationLogColumns // columns contains all the column names of Table for convenient usage.
}

// GoadminOperationLogColumns defines and stores column names for table goadmin_operation_log.
type GoadminOperationLogColumns struct {
	Id        string //
	UserId    string //
	Path      string //
	Method    string //
	Ip        string //
	Input     string //
	CreatedAt string //
	UpdatedAt string //
}

//  goadminOperationLogColumns holds the columns for table goadmin_operation_log.
var goadminOperationLogColumns = GoadminOperationLogColumns{
	Id:        "id",
	UserId:    "user_id",
	Path:      "path",
	Method:    "method",
	Ip:        "ip",
	Input:     "input",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewGoadminOperationLogDao creates and returns a new DAO object for table data access.
func NewGoadminOperationLogDao() *GoadminOperationLogDao {
	return &GoadminOperationLogDao{
		group:   "default",
		table:   "goadmin_operation_log",
		columns: goadminOperationLogColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *GoadminOperationLogDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *GoadminOperationLogDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *GoadminOperationLogDao) Columns() GoadminOperationLogColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *GoadminOperationLogDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *GoadminOperationLogDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *GoadminOperationLogDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
