// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-21 20:57:03
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Books is the golang structure of table books for DAO operations like Where/Data.
type Books struct {
	g.Meta      `orm:"table:books, do:true"`
	Id          interface{} //
	Name        interface{} //
	Author      interface{} //
	Description interface{} //
	Ebook       interface{} //
	Cover       interface{} //
	Price       interface{} //
	CreatedAt   *gtime.Time //
	Category    interface{} //
}
