// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-04-28 22:43:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Categories is the golang structure of table categories for DAO operations like Where/Data.
type Categories struct {
	g.Meta `orm:"table:categories, do:true"`
	Id     interface{} //
	Name   interface{} //
}
