// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-21 20:57:03
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// GoadminOperationLog is the golang structure of table goadmin_operation_log for DAO operations like Where/Data.
type GoadminOperationLog struct {
	g.Meta    `orm:"table:goadmin_operation_log, do:true"`
	Id        interface{} //
	UserId    interface{} //
	Path      interface{} //
	Method    interface{} //
	Ip        interface{} //
	Input     interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
