// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-21 20:57:03
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// GoadminRoles is the golang structure of table goadmin_roles for DAO operations like Where/Data.
type GoadminRoles struct {
	g.Meta    `orm:"table:goadmin_roles, do:true"`
	Id        interface{} //
	Name      interface{} //
	Slug      interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
