// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-21 20:57:03
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// GoadminUserPermissions is the golang structure of table goadmin_user_permissions for DAO operations like Where/Data.
type GoadminUserPermissions struct {
	g.Meta       `orm:"table:goadmin_user_permissions, do:true"`
	UserId       interface{} //
	PermissionId interface{} //
	CreatedAt    *gtime.Time //
	UpdatedAt    *gtime.Time //
}
