// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-21 20:57:03
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// GoadminMenu is the golang structure of table goadmin_menu for DAO operations like Where/Data.
type GoadminMenu struct {
	g.Meta     `orm:"table:goadmin_menu, do:true"`
	Id         interface{} //
	ParentId   interface{} //
	Type       interface{} //
	Order      interface{} //
	Title      interface{} //
	Icon       interface{} //
	Uri        interface{} //
	Header     interface{} //
	PluginName interface{} //
	Uuid       interface{} //
	CreatedAt  *gtime.Time //
	UpdatedAt  *gtime.Time //
}
