// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-21 20:57:03
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// GoadminRoleMenu is the golang structure of table goadmin_role_menu for DAO operations like Where/Data.
type GoadminRoleMenu struct {
	g.Meta    `orm:"table:goadmin_role_menu, do:true"`
	RoleId    interface{} //
	MenuId    interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
