// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-21 20:57:03
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// GoadminSession is the golang structure of table goadmin_session for DAO operations like Where/Data.
type GoadminSession struct {
	g.Meta    `orm:"table:goadmin_session, do:true"`
	Id        interface{} //
	Sid       interface{} //
	Values    interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
