// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-21 20:57:03
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// GoadminPermissions is the golang structure of table goadmin_permissions for DAO operations like Where/Data.
type GoadminPermissions struct {
	g.Meta     `orm:"table:goadmin_permissions, do:true"`
	Id         interface{} //
	Name       interface{} //
	Slug       interface{} //
	HttpMethod interface{} //
	HttpPath   interface{} //
	CreatedAt  *gtime.Time //
	UpdatedAt  *gtime.Time //
}
