// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-24 08:39:46
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ShoppingCarts is the golang structure of table shopping_carts for DAO operations like Where/Data.
type ShoppingCarts struct {
	g.Meta           `orm:"table:shopping_carts, do:true"`
	Id               interface{} //
	Sid              interface{} // 购物车id号
	CreatedAt        *gtime.Time //
	UpdateAt         *gtime.Time //
	BookShoppingCart interface{} //
	UserShoppingCart interface{} //
}
