// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-08 10:11:50
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ShoppingCarts is the golang structure of table shopping_carts for DAO operations like Where/Data.
type ShoppingCarts struct {
	g.Meta           `orm:"table:shopping_carts, do:true"`
	Id               interface{} //
	Amount           interface{} //
	CreatedAt        *gtime.Time //
	UpdateAt         *gtime.Time //
	BookShoppingCart interface{} //
	UserShoppingCart interface{} //
}
