// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-24 08:39:46
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Books is the golang structure for table books.
type Books struct {
	Id          int64       `json:"id"          description:""`
	Name        string      `json:"name"        description:""`
	Author      string      `json:"author"      description:""`
	Description string      `json:"description" description:""`
	Ebook       string      `json:"ebook"       description:""`
	Cover       string      `json:"cover"       description:""`
	Price       float64     `json:"price"       description:""`
	CreatedAt   *gtime.Time `json:"createdAt"   description:""`
	Category    string      `json:"category"    description:""`
}
