// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-08 10:11:50
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Books is the golang structure for table books.
type Books struct {
	Id           int64       `json:"id"           description:""`
	Name         string      `json:"name"         description:""`
	Author       string      `json:"author"       description:""`
	Description  string      `json:"description"  description:""`
	Ebook        string      `json:"ebook"        description:""`
	Cover        string      `json:"cover"        description:""`
	Price        int64       `json:"price"        description:""`
	CreatedAt    *gtime.Time `json:"createdAt"    description:""`
	CategoryBook int64       `json:"categoryBook" description:""`
}
