// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-21 20:57:03
// =================================================================================

package entity

// Categories is the golang structure for table categories.
type Categories struct {
	Id   int64  `json:"id"   description:""`
	Name string `json:"name" description:""`
}
