// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-21 20:57:03
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// GoadminRoleMenu is the golang structure for table goadmin_role_menu.
type GoadminRoleMenu struct {
	RoleId    uint        `json:"roleId"    description:""`
	MenuId    uint        `json:"menuId"    description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
}
