// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-21 20:57:03
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// GoadminOperationLog is the golang structure for table goadmin_operation_log.
type GoadminOperationLog struct {
	Id        uint        `json:"id"        description:""`
	UserId    uint        `json:"userId"    description:""`
	Path      string      `json:"path"      description:""`
	Method    string      `json:"method"    description:""`
	Ip        string      `json:"ip"        description:""`
	Input     string      `json:"input"     description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
}
