// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-21 20:57:03
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// GoadminSession is the golang structure for table goadmin_session.
type GoadminSession struct {
	Id        uint        `json:"id"        description:""`
	Sid       string      `json:"sid"       description:""`
	Values    string      `json:"values"    description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
}
