// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-21 20:57:03
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// GoadminPermissions is the golang structure for table goadmin_permissions.
type GoadminPermissions struct {
	Id         uint        `json:"id"         description:""`
	Name       string      `json:"name"       description:""`
	Slug       string      `json:"slug"       description:""`
	HttpMethod string      `json:"httpMethod" description:""`
	HttpPath   string      `json:"httpPath"   description:""`
	CreatedAt  *gtime.Time `json:"createdAt"  description:""`
	UpdatedAt  *gtime.Time `json:"updatedAt"  description:""`
}
