// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-21 20:57:03
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// GoadminUsers is the golang structure for table goadmin_users.
type GoadminUsers struct {
	Id            uint        `json:"id"            description:""`
	Username      string      `json:"username"      description:""`
	Password      string      `json:"password"      description:""`
	Name          string      `json:"name"          description:""`
	Avatar        string      `json:"avatar"        description:""`
	RememberToken string      `json:"rememberToken" description:""`
	CreatedAt     *gtime.Time `json:"createdAt"     description:""`
	UpdatedAt     *gtime.Time `json:"updatedAt"     description:""`
}
