// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-21 20:57:03
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// GoadminRoles is the golang structure for table goadmin_roles.
type GoadminRoles struct {
	Id        uint        `json:"id"        description:""`
	Name      string      `json:"name"      description:""`
	Slug      string      `json:"slug"      description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
}
