// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-21 20:57:03
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// GoadminSite is the golang structure for table goadmin_site.
type GoadminSite struct {
	Id          uint        `json:"id"          description:""`
	Key         string      `json:"key"         description:""`
	Value       string      `json:"value"       description:""`
	Description string      `json:"description" description:""`
	State       uint        `json:"state"       description:""`
	CreatedAt   *gtime.Time `json:"createdAt"   description:""`
	UpdatedAt   *gtime.Time `json:"updatedAt"   description:""`
}
