// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-21 20:57:03
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// GoadminRoleUsers is the golang structure for table goadmin_role_users.
type GoadminRoleUsers struct {
	RoleId    uint        `json:"roleId"    description:""`
	UserId    uint        `json:"userId"    description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
}
