// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-08 10:11:50
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Orders is the golang structure for table orders.
type Orders struct {
	Id        int64       `json:"id"        description:""`
	Amount    int64       `json:"amount"    description:""`
	Status    string      `json:"status"    description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdateAt  *gtime.Time `json:"updateAt"  description:""`
	BookOrder int64       `json:"bookOrder" description:""`
	UserOrder int64       `json:"userOrder" description:""`
}
