// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-24 08:39:46
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Orders is the golang structure for table orders.
type Orders struct {
	Id        int64       `json:"id"        description:""`
	Oid       int64       `json:"oid"       description:"订单id号"`
	Status    string      `json:"status"    description:"订单状态"`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdateAt  *gtime.Time `json:"updateAt"  description:""`
	BookOrder int64       `json:"bookOrder" description:""`
	UserOrder int64       `json:"userOrder" description:""`
}
