// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-10 14:06:06
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ShoppingCarts is the golang structure for table shopping_carts.
type ShoppingCarts struct {
	Id               int64       `json:"id"               description:""`
	Sid              int         `json:"sid"              description:"购物车id号"`
	CreatedAt        *gtime.Time `json:"createdAt"        description:""`
	UpdateAt         *gtime.Time `json:"updateAt"         description:""`
	BookShoppingCart int64       `json:"bookShoppingCart" description:""`
	UserShoppingCart int64       `json:"userShoppingCart" description:""`
}
