// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-08 10:11:50
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Users is the golang structure for table users.
type Users struct {
	Id        int64       `json:"id"        description:""`
	Username  string      `json:"username"  description:""`
	Password  string      `json:"password"  description:""`
	Type      string      `json:"type"      description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
}
